### ISSUE TITLE
Password validation

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/jogging-dolphins#52]
It's great that you're enforcing strong(ish) passwords. It is a bit difficult to sign up though as there's no indication to the user what format is required. I had to read the regex in devtools to figure out how to register :)

If you don't want to do fully custom error messages you can at least set a custom message as the `title` attribute. This will then show up in the default validation popup tooltip thing.

<img width="1121" alt="Screenshot 2019-04-19 at 10 08 35" src="https://user-images.githubusercontent.com/9408641/56417251-36bf6580-628b-11e9-8bfe-988188ce1d71.png">

**Comment by starsuit** [comment]
Seconded...
